services:
  mysql:
    image: mysql:5.7.32
    container_name: mysql_vacation
    volumes:
      - $HOME/mysql_vacation:/var/lib/mysql/
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    command: mysqld --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: mysql -e 'SELECT 1' 2>/dev/null || mysql -uroot -psecret -e 'SELECT 1' 2>/dev/null || exit 1